### ISSUE TITLE
Single quotes in input aren't escaped

### ISSUE THREAD

**Issue by j4james** [catseye/Falderal#8]
This is not something I use in Windows, but I noticed it while browsing the source code, and it looks to me like it's probably a bug. In the section of the code where the `%(test-input-text)` parameter is substituted, the content comes from the _input_ variable, but the single quote escaping is performed on the _body_ variable.

I'm referring to [this code](https://github.com/catseye/Falderal/blob/master/src/falderal/objects.py#L799-L802):

    # escape all single quotes in input
    body = re.sub(r"'", r"\'", body)
    # replace all occurrences in command
    command = re.sub(r'\%\(test-input-text\)', input, command)

I'm guessing that second line should be:

    input = re.sub(r"'", r"\'", input)

**Comment by cpressey** [comment]
That does indeed look wrong, based entirely on reading the code. What surprises me is that I've never noticed it causing a problem (perhaps I've never used a single quote in a test body, ever...?) I'll try to write a failing test, then fix it, then run it against all the Falderal test suites I've got, and see what happens.

**Comment by cpressey** [comment]
OK, after investigating: this is a bug, in the sense that it's not consistent with how `%(test-body-text)` works. I've never encountered it because it seems I've never used `%(test-input-text)` in any of my Falderal documents. I also haven't used `%(test-body-text)` as often as I thought I had.

However: how `%(test-body-text)` works is also ill-considered.

When I have used `%(test-body-text)` in my tests, I've often put it in single quotes, like

    is implemented by shell command "python echo.py '%(test-body-text)'"

and in this context, quoting single quotes in the substitution text actually won't work. In fact, shell quoting behaviour is nightmarish, and how you would want to quote the substitution text depends on what kind of quotes you expect to be put around it in the template string.

I think the only reasonable approach would be to make Falderal responsible for quoting _all_ the shell metacharacters in the substitution text, and expect _no_ quotes to be put around it, in the template string.

Turns out Python does have a function for this: [shlex.quote](https://docs.python.org/3/library/shlex.html#shlex.quote).

Since it makes so much more sense (and since I have so few tests that would have to be updated), I think I'd like to make that approach be the official behaviour for both `%(test-body-text)` and `%(test-input-text)`, in version 0.12.

**Comment by j4james** [comment]
If you want a python2 equivalent of `shlex.quote`, you could always use [`pipes.quote`](https://docs.python.org/2/library/pipes.html#pipes.quote). Unfortunately it seems that the quoting in those functions is nix-specific - the Windows rules are completely different - but that's probably not something you want to worry about it.

**Comment by cpressey** [comment]
Thanks, I was not aware of `pipes.quote`. I'll opt for using it instead of my hand-rolled version (which was illuminating to write, but it's too l likely that I missed a case or two in it.)

As long as the spec says that Falderal is responsible for all quoting during variable expansion, then, if and when it comes to making a version of the tool that runs on Windows, as long as the tool handles it properly there, that should be sufficient.

That said, I'm now no longer convinced `%(test-body-text)` and `%(test-input-text)` were even particularly good ideas anyway, considering how little I've used them, and that I can't remember exactly why they were introduced. But I think the basic principle is a good one, and should stay, for the benefit of the other variables, and any possible future ones.

**Comment by cpressey** [comment]
Closing this issue, as this fix(/improvement) has been released now.  Thanks for spotting it and bringing it up!
